### ISSUE TITLE
[Feature Request] Navigation buttons long press actions.

### ISSUE THREAD

**Issue by nihal697** [DroidX-UI/frameworks_base#16]
Hi, first and foremost sincere apologies if this is not acceptable , no mean to sound ungrateful or be rude.
I was just wondering if this implementation can be done just like there is in lineageos, crdroid (has a bit more actions but doesnt matter much). I find this feature quite useful for doing some things quickly.
(the last four options only, home/back/recents long press and double tap)
pfa
![Screenshot_20231212-180057_LineageOS Settings](https://github.com/DroidX-UI/frameworks_base/assets/47318989/715d0318-4b3c-49fd-86cd-e3aff98096f9)
![Screenshot_20231212-180107_LineageOS Settings](https://github.com/DroidX-UI/frameworks_base/assets/47318989/3dc2ead7-4992-4631-b0db-750e33587bfc)

**Comment by hipexscape** [comment]
Hi 
We reviewed your issues and I am happy to tell you that we will implement this feature in DroidX v2.0 

Thanks

**Comment by nihal697** [comment]
> Hi We reviewed your issues and I am happy to tell you that we will implement this feature in DroidX v2.0
> 
> Thanks

Hi, Thanks for the consideration. If Im not incorrect , v2.0 would be android 14 right?

**Comment by hipexscape** [comment]
> > Hi We reviewed your issues and I am happy to tell you that we will implement this feature in DroidX v2.0
> > Thanks
> 
> Hi, Thanks for the consideration. If Im not incorrect , v2.0 would be android 14 right?

Yes !

**Comment by nihal697** [comment]
Hi, just wanted to know if this feature is now in droidxui?

**Comment by nihal697** [comment]
Hi, can this be reopened so it might be added someday ?
